### ISSUE TITLE
in equals method, boolean vs Boolean?

### ISSUE THREAD

**Issue by thisfinalcode** [lzhengem/Java111b_Assignment5_Temperature#16]
In the equals method, we have the boolean return type, but Boolean variable

```
    public boolean equals(Temperature otherTemp){
        Boolean return_val = false;
        if(getC() == otherTemp.getC()){
            return_val = true;
        }
        return return_val;
    }
```

does this matter?

**Comment by Nickles255** [comment]
The one I put in is an object wrapper instead of a primitive type. I don't think it matters much as a matter of results in the code because the wrapper just adds more functionality. As a matter of returning a primitive type, it is a typo.


https://stackoverflow.com/questions/1295170/whats-the-difference-between-boolean-and-boolean-in-java

Java has primitive types (int, boolean, float, etc) and anytime you wish to use them as an instance of an object they are wrapped in an associated Class type. For example, booleans get wrapped by Booleans, int as Integer etc.It has its benefits too. boolean has no helper methods (since it's not a class), but Boolean does. So, if you wanted to convert a string to a boolean you could try Boolean.valueOf("true").
-- | --

**Comment by Nickles255** [comment]
changed from object wrapper to primitive type.
